apiVersion: v1
kind: ServiceAccount
metadata:
  name: anystatus-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
  name: anystatus-read-only
  namespace: default
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get","list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: anystatus-binding
subjects:
- kind: ServiceAccount
  name: anystatus-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: anystatus-read-only
  apiGroup: rbac.authorization.k8s.io